### ISSUE TITLE
Stucked to: Connecting to the Docker endpoint... 

### ISSUE THREAD

**Issue by pascalandy** [portainer/portainer-compose#12]
Hey Tony!

I'm running a docker stack with Traefik, Wordpress, Nginx, Caddy, Whoami and Portainer.
For some reason Portainer don't want to launch ...

<img width="761" alt="screen shot 2017-09-20 at 11 14 21 pm" src="https://user-images.githubusercontent.com/6694151/30677488-f07a794e-9e59-11e7-9f24-2b8e6add3933.png">

Do you want to [take a look](https://github.com/pascalandy/docker-stack-this/tree/master/traefik-manager-noacme)? You'll see you can run the whole stack via one command via play-with-docker. 

I would really like to have Portainer to be part of this Docker Stack boiler template.

Thanks in advance!
Pascal

**Comment by deviantony** [comment]
Hey @pascalandy 

I had a quick look, I think that this might be related to the reverse proxy configuration. 

Are you sure about the traefik options passed here:

```
      labels:
        - "traefik.backend=portainer"
        - "traefik.frontend.rule=PathPrefixStrip:/portainer"
        - "traefik.port=9000"
        - "traefik.enable=true"
        - "traefik.frontend.entryPoints=http"
        - "traefik.docker.network=ntw_front"
        - "traefik.weight=10"
        - "traefik.frontend.passHostHeader=true"
```

**Comment by pascalandy** [comment]
Good catch! I updated the stack.

Traefik was having issue about this few months ago and they fixed this. know there is now labels to handle this use case. 

Many many cheers!

**Comment by pascalandy** [comment]
Still the same issue here @kylesnipes. You can try my stack [here](https://github.com/pascalandy/docker-stack-this/tree/master/traefik_stack5). Cheers!

**Comment by ttresse** [comment]
Hello
I have the same issue here ! Any news ?

**Comment by Dave3991** [comment]
Hello,
same problem here (traefik 1.6) , any updates ?

**Comment by sconnery** [comment]
Hey guys,
simmilar issue here with nginx, was working initially now its stuck at this point. I followed the config guide

**Comment by sconnery** [comment]
Just following up on the above comment

**Comment by exNewbie** [comment]
@sconnery surely nobody cares about this issue. I also contacted them on Slack but got ignored :|

**Comment by sconnery** [comment]
yep i did as well :(
trying 2 docker servers to try this.

**Comment by deviantony** [comment]
Shipping this compose setup with a valid reverse proxy configuration (using `jwilder/nginx`), should be fixed via https://github.com/portainer/portainer-compose/pull/20

**Comment by sconnery** [comment]
Any guide on how sorry?

Thanks
