### ISSUE TITLE
New container but it have account

### ISSUE THREAD

**Issue by monburan** [portainer/portainer-compose#13]
Hello,I use portainer-composer for a while, it's very handy . Until I forgot portainer's account password some day last week. I try to remove all containers , all images , and all volumes of portainer-compose ,restart docker and rebuild it , but I failed . the portainer allways have an admin account that I do not know the password . Portainer can't reset admin account , what should I do ?

**Comment by deviantony** [comment]
Hey @monburan,

As you don't have the ability to reset the admin password yet (see https://github.com/portainer/portainer/issues/512), you'll need to wipe out the data folder of Portainer.

How did you start Portainer? Did you persist the data on your host? You'll need to remove the folder on your host if that's the case.

**Comment by monburan** [comment]
Thank you!!!This is really too helpful!!!

**Comment by deviantony** [comment]
Closing this issue.
