### ISSUE TITLE
starting portainer on boot when using docker-compose.yml

### ISSUE THREAD

**Issue by DoTheEvo** [portainer/portainer-compose#17]
When I google it seem people prefer going `restart: always`
is there a preferred, recommended method for portainer-compose?

- should i add restart always myself?
- use systemd unit?
- use crony?

**Comment by deviantony** [comment]
Hi @DoTheEvo 

This setup has not been updated since more than a year now and might be a bit deprecated. It is indeed recommended to use `restart: always` to ensure that the Portainer container is still running after your host reboot.

**Comment by deviantony** [comment]
Updated via https://github.com/portainer/portainer-compose/commit/fac9f0add983e4e41ffcab3e100d92d5ccc737fb
