### ISSUE TITLE
Typo in docker-compose.yml

### ISSUE THREAD

**Issue by Fmstrat** [portainer/portainer-compose#18]
I'm a total newb to portainer, but I think there is a typo in the compose file.

At https://github.com/portainer/portainer-compose/blob/master/docker-compose.yml#L33 should that be `portainer-templates` not `portainer/templates`?

**Comment by deviantony** [comment]
Looks like you're right. We'll need to confirm this.

**Comment by deviantony** [comment]
Fixed via https://github.com/portainer/portainer-compose/pull/20
