### ISSUE TITLE
Set new container environment variables in bulk

### ISSUE THREAD

**Issue by khalidrehan** [portainer/portainer-compose#26]
Hello,
Is there someway to set environment variables other than one by one on the new/edit container screen? There has to be another way!

Regards,
Khalid.

**Comment by deviantony** [comment]
Hi @khalidrehan,

we're currently working on revamping some of the UX/UI around environments variables via https://github.com/portainer/portainer/pull/4175

This should address your concerns here as well as the one reported in the following issues:

* https://github.com/portainer/portainer/issues/546
* https://github.com/portainer/portainer/issues/1857

Closing in favor of #546
