### ISSUE TITLE
Authentification conflict with the last version of portainer

### ISSUE THREAD

**Issue by Nightbr** [portainer/portainer-compose#6]
Hello,

since the last release of portainer https://github.com/portainer/portainer/releases/tag/1.11.0, it intergrates a simple authentification mechanism. So the watchtower upgrades successfully my portainer but I had some conflicts between htpasswd and the simple authentification mechanism.

I decide to remove the .htpasswd, the linked conf and the COPY in order to only use the integrated auth from portainer. 

I think it would be great if there are several branch or tags (1.0, 1.1 or 2.0) in order to take this into account.

I can make a PR at the end of the week if you want but it is pretty simple (just remove all code/file related to htpasswd).

Thanks in advance and keep going with your great work!

**Comment by deviantony** [comment]
@Nightbr thanks for opening an issue, I just did not had the time to update the compose project... yet ! But it's going to be available soon. I'll keep a branch with http authentication aside.

**Comment by deviantony** [comment]
All right this project has been updated to match the latest version configuration. Also, previous work with HTTP authentication is available at https://github.com/portainer/portainer-compose/tree/http-auth
